DROP TABLE task_log IF EXISTS;
DROP TABLE task IF EXISTS;
DROP TABLE workstation IF EXISTS;
DROP TABLE employee IF EXISTS;

-- -------------------------
-- Table: employee
-- -------------------------
CREATE TABLE employee (
                          id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
                          employee_code   VARCHAR(20) NOT NULL,
                          full_name       VARCHAR(120) NOT NULL,
                          email           VARCHAR(120),
                          is_active       BOOLEAN DEFAULT TRUE NOT NULL,
                          created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                          CONSTRAINT employee_pk PRIMARY KEY (id),
                          CONSTRAINT employee_code_uq UNIQUE (employee_code),
                          CONSTRAINT employee_email_uq UNIQUE (email)
);

-- -------------------------
-- Table: workstation
-- -------------------------
CREATE TABLE workstation (
                             id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
                             code          VARCHAR(20) NOT NULL,
                             name          VARCHAR(80) NOT NULL,
                             area          VARCHAR(80),
                             is_active     BOOLEAN DEFAULT TRUE NOT NULL,
                             created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                             CONSTRAINT workstation_pk PRIMARY KEY (id),
                             CONSTRAINT workstation_code_uq UNIQUE (code)
);

-- -------------------------
-- Table: task
-- -------------------------
CREATE TABLE task (
                      id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
                      task_code       VARCHAR(30) NOT NULL,
                      title           VARCHAR(200) NOT NULL,
                      description     VARCHAR(200),

    -- status: TODO / IN_PROGRESS / DONE / CANCELLED
                      status          VARCHAR(20) NOT NULL,

    -- priority: LOW / MEDIUM / HIGH
                      priority        VARCHAR(10) NOT NULL,

                      due_date        DATE,

                      employee_id     BIGINT,
                      workstation_id  BIGINT,

                      created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                      CONSTRAINT task_pk PRIMARY KEY (id),
                      CONSTRAINT task_code_uq UNIQUE (task_code),

                      CONSTRAINT task_status_ck CHECK (status IN ('TODO','IN_PROGRESS','DONE','CANCELLED')),
                      CONSTRAINT task_priority_ck CHECK (priority IN ('LOW','MEDIUM','HIGH')),

                      CONSTRAINT task_employee_fk FOREIGN KEY (employee_id) REFERENCES employee(id),
                      CONSTRAINT task_workstation_fk FOREIGN KEY (workstation_id) REFERENCES workstation(id)
);

CREATE INDEX idx_task_status ON task(status);
CREATE INDEX idx_task_employee ON task(employee_id);
CREATE INDEX idx_task_workstation ON task(workstation_id);

-- -------------------------
-- Table: task_log
-- -------------------------
CREATE TABLE task_log (
                          id                     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
                          task_id                BIGINT NOT NULL,

    -- event_type: CREATED / STATUS_CHANGE / COMMENT / ASSIGNMENT_CHANGE
                          event_type             VARCHAR(30) NOT NULL,

                          old_status             VARCHAR(20),
                          new_status             VARCHAR(20),

                          message                VARCHAR(200),

                          created_by_employee_id BIGINT,
                          created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                          CONSTRAINT task_log_pk PRIMARY KEY (id),
                          CONSTRAINT task_log_task_fk FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE,
                          CONSTRAINT task_log_created_by_fk FOREIGN KEY (created_by_employee_id) REFERENCES employee(id),

                          CONSTRAINT task_log_event_type_ck CHECK (event_type IN ('CREATED','STATUS_CHANGE','COMMENT','ASSIGNMENT_CHANGE')),
                          CONSTRAINT task_log_status_ck CHECK (
                              (old_status IS NULL OR old_status IN ('TODO','IN_PROGRESS','DONE','CANCELLED'))
                                  AND
                              (new_status IS NULL OR new_status IN ('TODO','IN_PROGRESS','DONE','CANCELLED'))
                              )
);

CREATE INDEX idx_task_log_task_id ON task_log(task_id);
